// 英文肯定语库（与 index.html cats[].cards 一一对应）
window.AFF_EN = {
  love: [
    "I am worthy of being deeply loved, and true love is making its way to me.",
    "I attract love that is gentle, real, and profound.",
    "My heart is open, and beautiful relationships flow to me naturally.",
    "I deserve a love that makes me feel safe and cherished.",
    "As I love myself well, love returns to me in the very same way.",
    "I deserve to be treated tenderly, and I am able to treat others with tenderness too.",
    "I attract people who share my frequency, and we nourish one another.",
    "I release the wounds of the past to make room for new love.",
    "In my relationships I can be both intimate and free.",
    "I trust that the right person will arrive at exactly the right time.",
    "My love is abundant, and the more I give, the more returns to me.",
    "I allow myself to be seen, understood, and treasured.",
    "I don’t have to be perfect to be loved completely.",
    "My connection with the ones I love deepens a little more each day.",
    "I invite people who respect and support me into my life.",
    "I deserve a relationship that helps us both become better people.",
    "My love life is full of warmth, trust, and laughter.",
    "I know how to express my needs, and how to truly listen.",
    "I radiate the light of love, and people are drawn to come close.",
    "Right now, I am loved, with no conditions at all."
  ],
  wealth: [
    "Money comes to me easily; I was born to be abundant.",
    "I can earn everything I desire, and more and more of it.",
    "Wealth adores me, and opportunities are always finding me.",
    "Financial freedom is mine; it is only a matter of time.",
    "I am worthy of abundance, and money is simply one of its forms.",
    "My income is growing steadily and surely.",
    "My relationship with money is easy and open.",
    "The universe’s resources are limitless, and my share is on its way.",
    "I treat money as a friend, and it is glad to walk beside me.",
    "I allow myself to be prosperous, and I allow myself to enjoy it.",
    "Every dollar I spend brings even more flowing back to me.",
    "My talents and worth deserve to be richly rewarded.",
    "Wonderful ways to earn keep pouring toward me.",
    "I use money to create beauty and to help others.",
    "I trust my ability to manage and multiply my wealth.",
    "Abundance is my natural state; I am simply returning to it.",
    "The more grateful I am, the more I have.",
    "I deserve a life free from worrying about money.",
    "Wealth flows freely to me, and freely through me.",
    "Right now, abundance is already here in my life."
  ],
  health: [
    "My body is strong, and it grows better every single day.",
    "I am full of vitality, greeting each day with abundant energy.",
    "I love my body, and it answers my love with vibrant life.",
    "Life force flows through me, and I feel light and strong.",
    "Every cell in my body is filled with health and light.",
    "I treat my body with kindness, and it responds to me with tenderness.",
    "I sleep deeply and wake up refreshed and clear.",
    "My body knows how to heal itself, and I trust it.",
    "I choose the food and the way of living that nourish me.",
    "The deeper I breathe, the calmer and stronger I feel.",
    "My body and mind are in harmony and balance.",
    "I deserve a healthy body full of vitality.",
    "I listen to my body’s signals and give it the rest it needs.",
    "Each day, I become healthier and more alive.",
    "I release stress and let health flow naturally back into me.",
    "My immune system is strong and it protects me.",
    "Movement brings me joy, and my body feels lighter for it.",
    "I am grateful for everything my body does for me.",
    "I have a never-ending supply of energy for all I wish to do.",
    "Right now, my body is safe and healthy."
  ],
  conf: [
    "I can do this; I really can.",
    "I can accomplish anything I decide to do.",
    "I believe in myself, and my judgment is sound.",
    "I am good enough; who I am right now is already enough.",
    "I have every right to take up the space that is mine.",
    "My voice deserves to be heard.",
    "I don’t need anyone’s approval to prove my worth.",
    "I meet challenges with ease, because I trust myself.",
    "I like my true self more and more.",
    "My very presence is a kind of power.",
    "I allow myself to shine, without shrinking.",
    "It’s okay to make mistakes; I grow stronger through them.",
    "I am worthy of everything I long for.",
    "I go after what I want with quiet confidence.",
    "My confidence comes from within and does not depend on the outside world.",
    "I can handle any situation with grace.",
    "I respect myself, and I earn the respect of others.",
    "Day by day, I grow more certain and more powerful.",
    "I trust my intuition and my abilities.",
    "Right now, I am whole and powerful."
  ],
  career: [
    "I have the ability to do everything I set out to do.",
    "Good opportunities always appear before me at just the right moment.",
    "My efforts will surely pay off; I deserve success.",
    "I can reach my goals, one step at a time; I can do this.",
    "In my field, I grow more skilled and more recognized every day.",
    "I attract like-minded collaborators and helpful allies.",
    "My work gives me fulfillment and brings me generous rewards.",
    "I dare to reach for a bigger stage.",
    "Every challenge is a step upward in my growth.",
    "I know clearly where I am headed, and I move forward steadily.",
    "My talents are being seen by more and more people.",
    "I deserve promotions, raises, and greater opportunities.",
    "I turn what I love into my work, and my work into what I love.",
    "I make decisions with decisiveness and clarity.",
    "Success is my natural direction.",
    "I allow myself to succeed with both effort and ease.",
    "Every bit of effort I give is building the fruit of my future.",
    "I have the ability and the right to pursue excellence.",
    "I trust that I can create the career I want.",
    "Right now, I am walking the path toward success."
  ],
  peace: [
    "I can let go of worry; everything will be okay.",
    "I allow myself to slow down; peace is my right.",
    "I am okay; in this moment, I am safe.",
    "I can handle everything in my life; I am stronger than I think.",
    "I bring my attention back to this moment, and here it is steady.",
    "I breathe deeply and let the tension loosen, little by little.",
    "I don’t have to control everything; I can trust life.",
    "Within me there is a place that is forever still.",
    "I set down the weight that was never mine to carry.",
    "I allow myself to rest; it is okay to do nothing at all.",
    "Peace rises from within me, undisturbed by the outside world.",
    "I treat the person I am in this moment with tenderness.",
    "I accept everything as it is, just as it is.",
    "My heart grows calm, like the still surface of a lake.",
    "I deserve serenity and ease.",
    "I release anxiety and choose trust.",
    "Everything is unfolding at exactly the pace it should.",
    "Even amid chaos, I can find my center.",
    "I let peace become the ground tone of who I am.",
    "Right now, I am safe and supported."
  ],
  charm: [
    "I am magnetic; I attract good people and good things.",
    "I like myself more and more, and I truly am lovely.",
    "My very existence has value, and people like me.",
    "I confidently be myself, and that is my greatest charm.",
    "I radiate a warm and enchanting light.",
    "What makes me unique is exactly where my charm lies.",
    "People are drawn to my authentic energy.",
    "The more relaxed I am being myself, the more magnetic I become.",
    "I deserve to be admired and adored.",
    "My smile can light up a whole room.",
    "I glow with confidence from the inside out.",
    "I attract people who appreciate me and treat me kindly.",
    "I love the person I see in the mirror.",
    "My presence makes people want to come near.",
    "My charm comes from fully accepting myself.",
    "I grow more stylish and more self-assured every day.",
    "I deserve to be the one who is seen.",
    "I move the people around me with my sincerity.",
    "My energy is gentle and powerful at once.",
    "Right now, I am full of charm."
  ],
  create: [
    "My mind is full of good ideas, and there are more and more of them.",
    "I can create things that make me proud.",
    "Inspiration always arrives just when I need it.",
    "I have the power to turn ideas into reality; I can do this.",
    "Creativity flows freely within me.",
    "I allow myself to express and create boldly.",
    "I trust my own unique perspective.",
    "Every idea is a seed worth planting.",
    "The more I play, the richer my inspiration grows.",
    "I am not afraid to make mistakes; creating is itself an act of exploring.",
    "My imagination is limitless.",
    "I turn the everyday into a source of inspiration.",
    "I deserve to feel proud of my own work.",
    "Inspiration loves to flow toward an open heart.",
    "I have the courage to make the pictures in my mind real.",
    "My creativity grows a little more every day.",
    "I let my work be finished first, and perfected later.",
    "I am a creator by nature.",
    "I trust that I can make something truly one of a kind.",
    "Right now, inspiration is rushing toward me."
  ],
  family: [
    "My home is full of love, and it grows better every day.",
    "I can be a good member of my family; I am trying, and that is enough.",
    "Love flows through our home, and we support one another.",
    "I use love as a bridge to deepen every family bond.",
    "Our home is a warm and safe harbor.",
    "I accompany the ones I love with patience and understanding.",
    "My relationships with my family are gently healing and growing.",
    "I allow myself, and I allow my family, to be truly ourselves.",
    "We hold space for one another within love.",
    "I bring calm and steady energy to my family.",
    "I know how to listen, and how to express love.",
    "There is a deep connection between me and my family.",
    "Our home is full of laughter and understanding.",
    "I care for myself first, so I can love my family even better.",
    "I release old family wounds and choose a new way of being together.",
    "I deserve family relationships that support me.",
    "Love and gratitude are the ground tone of our home.",
    "My actions let my family feel cherished.",
    "We grow together, and we become better together.",
    "Right now, my home is full of love."
  ],
  protect: [
    "I have the right to say no; my feelings matter.",
    "I protect my energy and keep away from what drains me.",
    "I can set boundaries; this is not selfish, it is loving myself.",
    "I am strong enough that no negativity can affect me.",
    "My boundaries are clear and firm.",
    "I allow myself to make my own care a priority.",
    "I have the right to refuse anything that makes me uncomfortable.",
    "I take responsibility for my own time and energy.",
    "I guard my space gently and firmly.",
    "I don’t have to please everyone.",
    "I deserve to be surrounded by people who respect my boundaries.",
    "I can love someone and protect myself at the same time.",
    "I gently release the relationships that drain me.",
    "My “no” is a “yes” to myself.",
    "I trust myself to know what is good for me.",
    "I feel no guilt for setting boundaries.",
    "I build a shield that is gentle yet strong.",
    "I deserve relationships that are safe and respectful.",
    "I am in charge of my own energy and choices.",
    "Right now, I am safe, and I am powerful."
  ],
  spirit: [
    "I am growing every day; today I am better than I was yesterday.",
    "I trust that life is guiding me toward a better place.",
    "I can feel the wisdom within me, and I trust it.",
    "I am on the right path, and everything is moving in a good direction.",
    "I stay connected to my higher self.",
    "Every experience is teaching me the lesson I need.",
    "I trust the rhythm and the timing of life.",
    "I am learning more and more to listen to my inner voice.",
    "I allow myself to awaken at my own pace.",
    "I am a being tenderly watched over by the universe.",
    "I let go of control and open myself to life.",
    "My soul knows where it is going.",
    "In stillness, I hear my guidance.",
    "I am grateful for every experience of this moment.",
    "I trust that beautiful things I cannot yet see are taking shape.",
    "I am connected to all things.",
    "I let the old self fall away, and the new self be born.",
    "A deeper meaning to my life is unfolding.",
    "I move through every stage carrying trust.",
    "Right now, I am being gently guided by life."
  ],
  release: [
    "I can let go of the past; I don’t have to keep holding it.",
    "I allow myself to get better; I deserve to be happy.",
    "I have already done my best, and that is enough.",
    "I can come through any hardship; I always have.",
    "I gently embrace the self who was once wounded.",
    "I release the emotions and stories that no longer belong to me.",
    "I let the tears flow, and I let them go.",
    "The past cannot define my future.",
    "I forgive myself, and slowly I forgive others too.",
    "I give myself the time I need to heal.",
    "I let go of “should” and accept “now.”",
    "Every day, the wound heals a little more.",
    "I deserve to be freed from what weighs on me.",
    "I hand my burdens over to time and to life.",
    "I no longer need to prove anything; I am already enough.",
    "I allow myself to begin again.",
    "I release the past and welcome lightness.",
    "Healing is not forgetting; it is making peace with myself.",
    "Little by little, I am finding my way back to myself.",
    "Right now, I choose to be kind to myself."
  ],
  akashic: [
    "I can connect to the deepest wisdom of the universe; the answer is within me.",
    "My soul holds a record of everything, and I trust the guidance it gives.",
    "I can read the signs the universe sends me; everything has meaning.",
    "I am part of infinite wisdom, and I can receive every answer I need.",
    "I look within, and there I find all the guidance I need.",
    "I trust the journey my soul has arranged for me.",
    "Everyone I meet is a companion on my soul’s journey.",
    "I allow higher wisdom to flow through me.",
    "My intuition is the universe whispering to me.",
    "I am aligned with my soul’s mission.",
    "Every moment of confusion leads to a deeper understanding.",
    "I remember why I came here.",
    "In the silence, I receive the universe’s guidance.",
    "I trust the knowing that goes beyond reason.",
    "My soul is ancient and wise.",
    "I share one consciousness with all of life.",
    "I release my doubts and open to the answers within.",
    "I deserve clarity and guidance.",
    "The universe has always been answering my questions.",
    "Right now, the answer is already within my heart."
  ]
};
